In [4]:
# Import constant from TensorFlow
from tensorflow import constant,add
credit_numpy=[[1,2,3,4,5]]
# Convert the credit_numpy array into a tensorflow constant
credit_constant = constant(credit_numpy)

# Print constant datatype
print('The datatype is:', credit_constant.dtype)

# Print constant shape
print('The shape is:', credit_constant.shape)

The datatype is: <dtype: 'int32'>
The shape is: (1, 5)


In [5]:
a0=constant([1])

In [6]:
b0=constant([2])

In [7]:
add(a0,b0)

<tf.Tensor: id=5, shape=(1,), dtype=int32, numpy=array([3])>

In [8]:
import tensorflow as tf

In [10]:
A1 = constant([1, 2, 3, 4])
A23 = constant([[1, 2, 3], [1, 6, 4]])

In [12]:
B1 = tf.ones_like(A1)
B23 =  tf.ones_like(A23)

In [13]:
C1 = tf.multiply(A1,B1)
C23 = tf.multiply(A23,B23)

In [14]:
print('C1: {}'.format(C1.numpy()))
print('C23: {}'.format(C23.numpy()))

C1: [1 2 3 4]
C23: [[1 2 3]
 [1 6 4]]


In [15]:
# Define features, params, and bill as constants
features = constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = constant([[1000], [150]])
bill = constant([[3913], [2682], [8617], [64400]])

In [18]:
billpred = tf.matmul(features,params)

In [22]:
error = bill - billpred
print(error.numpy())

[[-1687]
 [-3218]
 [-1933]
 [57850]]


In [24]:
tf.reduce_sum(features).numpy()

151

In [25]:
tf.reduce_sum(features,0).numpy()

array([  7, 144])

In [26]:
tf.reduce_sum(features,1).numpy()

array([26, 28, 59, 38])